- name: "install mariadb"
  hosts: localhost
  order: sorted
  become: true
  tasks:
  - name: install java 11
    ansible.builtin.dnf: 
      name: java-11-openjdk
  - name: Install repo Mariadb
    ansible.builtin.get_url:
      url:  https://r.mariadb.com/downloads/mariadb_repo_setup
      dest: /tmp
  - name: exec script
    ansible.builtin.shell:
      cmd: curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup |sudo bash -s -- --mariadb-server-version="mariadb-11.0.1"
  - name: install java 11
    ansible.builtin.dnf: 
      name: MariaDB-server
      enablerepo: mariadb-main
  - name: Activer le service mariadb au démarrage
    ansible.builtin.systemd:
      name: mariadb
      enabled: yes
      state: started
